### ISSUE TITLE
No module named 'six.moves.urllib'

### ISSUE THREAD

**Issue by simplylu** [Jul10l1r4/getrails#6]
Fresh installed the lib via `pip3 install --user getrails`
Imported it into the Python 3.9.1 shell: `import getrails`
Got the following traceback:
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import getrails
  File "/home/user/.local/lib/python3.9/site-packages/getrails/__init__.py", line 1, in <module>
    from getrails.duckduckgo.search import go_duck
  File "/home/user/.local/lib/python3.9/site-packages/getrails/duckduckgo/search.py", line 2, in <module>
    import mechanicalsoup
  File "/home/user/.local/lib/python3.9/site-packages/mechanicalsoup/__init__.py", line 2, in <module>
    from .browser import Browser
  File "/home/user/.local/lib/python3.9/site-packages/mechanicalsoup/browser.py", line 3, in <module>
    from six.moves import urllib
  File "/usr/lib/python3.9/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/lib/python3.9/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3.9/site-packages/six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'six.moves.urllib'
```

Running on: `Linux hostname 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux`

**Comment by Jul10l1r4** [comment]
Thnx for issue, i'll see it

**Comment by Jul10l1r4** [comment]
This is problems of dependency, i want see it in test for identify like manjaro distros

**Comment by julioliraup** [comment]
I change project for my account
